-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id bigint generated always as identity NOT NULL,
    first_name character varying(30),
    last_name character varying(30),
    phone_number character varying(13),
    image_path text,
    email text,
    descriptions text,
    birth_date text,
    password_hash text,
    salt text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    amount real,
    status text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id bigint generated always as identity NOT NULL,
    category_name text,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    image_path text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    id bigint generated always as identity NOT NULL,
    category_id bigint NOT NULL,
    course_name text,
    price_per_month real,
    description text,
    image_path text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.videos
(
    id bigint generated always as identity NOT NULL,
    course_id bigint NOT NULL,
    image_path text,
    video_path text,
    video_descriptions text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint generated always as identity NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint,
    created_at timestamp without time zone,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.courses
    ADD FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.videos
    ADD FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;